[package]
name = "rust_array_ext"
version = "0.1.0"
edition = "2024"

[lib]
name = "rust_array_ext"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25", features = ["extension-module"] }
numpy = "0.25"
ndarray = "0.16.1"
